name: Dependency submission

on:
  schedule:
    # Hver onsdag kl. 04:00
    - cron: '0 4 * * 3'
  push:
    branches:
      - main
    paths:
      - gradle.properties
      - build.gradle.kts
      - settings.gradle.kts

jobs:
  dependency-submission:
    uses: navikt/hag-workflows/.github/workflows/dependency-submission.yml@main
    permissions:
      contents: write
